ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS status VARCHAR(16);
UPDATE documents SET status = 'DRAFT' WHERE status IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS visibility VARCHAR(16);
UPDATE documents SET visibility = 'SPACE' WHERE visibility IS NULL;

CREATE TABLE IF NOT EXISTS document_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  author VARCHAR(64) NOT NULL,
  content VARCHAR(4000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_doc_comments_doc_id ON document_comments(document_id);
