ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS status VARCHAR(16);
UPDATE documents SET status = 'DRAFT' WHERE status IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS visibility VARCHAR(16);
UPDATE documents SET visibility = 'SPACE' WHERE visibility IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS locked BOOLEAN;
UPDATE documents SET locked = FALSE WHERE locked IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS sort_order INTEGER;
UPDATE documents SET sort_order = 0 WHERE sort_order IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS owner VARCHAR(64);
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS editors VARCHAR(1024);
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS viewers VARCHAR(1024);
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS share_enabled BOOLEAN;
UPDATE documents SET share_enabled = FALSE WHERE share_enabled IS NULL;
ALTER TABLE IF EXISTS documents ADD COLUMN IF NOT EXISTS share_token VARCHAR(128);

CREATE TABLE IF NOT EXISTS document_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  author VARCHAR(64) NOT NULL,
  content VARCHAR(4000) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_doc_comments_doc_id ON document_comments(document_id);

CREATE TABLE IF NOT EXISTS document_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  original_file_name VARCHAR(255) NOT NULL,
  stored_file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(512) NOT NULL,
  content_type VARCHAR(128),
  file_size BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_doc_attachments_doc_id ON document_attachments(document_id);
